image: cm0x4d/ubuntu-qt5-cmake
stages:
    - build

build:
    stage: build
    script:
        # Get dependencies
        - apt-get --yes update
        - apt-get --yes install pkg-config libssl-dev zlib1g-dev wget
        - wget https://www.libssh.org/files/0.9/libssh-0.9.5.tar.xz
        - tar xf libssh-0.9.5.tar.xz
        - cd libssh-0.9.5
        - mkdir build
        - cd build
        - cmake ..
        - make install
        - cd ../..
        
        # Actually build and install QJournalctl
        - ./autogen.sh
        - make
        - ls -lh qjournalctl
